version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - database
    #   - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
      ENABLE_BOOTSNAP: "true"
    entrypoint: ./docker-entrypoint.sh

  # database:
  #   image: postgres:12-alpine
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_USER: root


  # redis:
  #   image: redis:6-alpine

  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - app
  #     - database
  #     - redis
  #   volumes:
  #     - .:/app
  #     - gem_cache:/usr/local/bundle/gems
  #     - node_modules:/app/node_modules
  #   env_file: .env
  #   environment:
  #     RAILS_ENV: development
  #     ENABLE_BOOTSNAP: "false"
  #   entrypoint: ./sidekiq-entrypoint.sh

volumes:
  gem_cache:
  db_data:
  node_modules: